### ISSUE TITLE
Packer error: Expected Lua number

### ISSUE THREAD

**Issue by jhossbach** [folke/todo-comments.nvim#85] opened 2022-01-16 13:05 UTC
Hey there,
since a few days I get an error in `lua/todo-comments/highlight.lua`, line 278 with `Expected Lua Number`.
It might be related to the latest API change for `nvim_buf_clear_namespace` (see https://github.com/neovim/neovim/issues/14090#issuecomment-1004318147).

**Comment by folke** [comment] 2022-01-19 14:19
Just pushed a fix for this. That line in the code actually never did what was intended, which resulted in the error being shown.

Fixed it now :)

**Closed by folke** 2022-01-19 14:19 UTC

**Comment by jhossbach** [comment] 2022-01-19 15:05
Happy to help :)
