### ISSUE TITLE
Navigation to prev/next todo-comment

### ISSUE THREAD

**Issue by axieax** [folke/todo-comments.nvim#77] opened 2021-12-02 16:30 UTC
Hi, just a feature request for todo-comment navigation which can be mapped to something like `[t` or `]t` for jumping to the previous and next todo-comment respectively, similar to [gitsigns.nvim](https://github.com/lewis6991/gitsigns.nvim)'s `prev_hunk()` and `next_hunk()` feature. I feel like this is a more efficient way to jump between issues, replacing the following laborious workflow every time you want to navigate to the prev/next todo-comments:
1. Open a picker from one of the :Todo commands
2. Navigating to the next todo-comment
3. Click enter to jump to that todo-comment
4. Close the todo window

I really love this plugin and would love to see this implemented :))

**Comment by diegoulloao** [comment] 2022-09-06 05:43
any new on this? totally necessary.

**Comment by folke** [comment] 2022-09-06 08:14
I just implemented this. 

Refer to the [docs](https://github.com/folke/todo-comments.nvim#jumping) to set this up.

**Comment by axieax** [comment] 2022-09-13 01:34
@folke I've just got around to testing out this feature and came across the following bug. It seems that the third NOTE is always skipped during navigation.

```lua
# NOTE: 1
# NOTE: 2
# NOTE: 3
...
# NOTE: 4
```

**Comment by folke** [comment] 2022-09-13 05:25
@axieax I'm not able to reproduce this. Can you post the exact text and filename you're using?

**Comment by axieax** [comment] 2022-09-13 05:48
Here's an example file I'm using (`test.lua`):

```lua
-- NOTE: 1
-- NOTE: 2
-- NOTE: 3

-- NOTE: 4
-- NOTE: 5
```

My config can be found [here](https://github.com/axieax/dotconfig/blob/5f4a8082d26507339372a7db8112d7e3607b31a0/nvim/lua/axie/plugins/notes.lua)

**Comment by folke** [comment] 2022-09-13 06:03
Good catch!

I just fixed this. There was an off-by-one error when checking if the found keyword is inside a comment.

Fixed now.

**Closed by folke** 2022-09-13 06:03 UTC
